[project]
name = "demo_transit_telemetry"
version = "0.0.1"
authors = [{ name = "linzi9506@gmail.com" }]
requires-python = ">=3.12,<3.13"
dependencies = []

[dependency-groups]
dev = [
    "databricks-connect==17.3.*",
    "ipykernel",
    "pytest",
    "ruff",
]

[tool.ruff]
line-length = 120
target-version = "py312"